# Generated by Django 3.2.25 on 2024-04-05 13:42

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12 PM - 2 PM', '12 PM - 2 PM'), ('1 PM - 3 PM', '1 PM - 3 PM'), ('2 PM - 4 PM', '2 PM - 4 PM'), ('3 PM - 5 PM', '3 PM - 5 PM'), ('4 PM - 6 PM', '4 PM - 6 PM'), ('5 PM - 7 PM', '5 PM - 7 PM'), ('6 PM - 8 PM', '6 PM - 8 PM')], max_length=60, null=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('guest_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.guest_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
