# Generated by Django 3.2.25 on 2024-04-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='image',
        ),
    ]
