# Generated by Django 4.2.11 on 2024-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_remove_reservations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
